### ISSUE TITLE
Curiosity or possible bug

### ISSUE THREAD

**Issue by gfr10598** [m-lab/tcp-info#101]
The K8S:TCPInfo dashboard shows that there are no bytes transmitted (or received) in the majority of 1 second intervals on the pilot machines.  

The median machine is only running about 1 test/minute.  This means that there is only an NDT test running about 20-25% of the time on individual machines.  If there is no other significant traffic, then it isn't unreasonable for 50 - 70% of the time to be idle.

**Comment by gfr10598** [comment]
Looking at the hottest machines, there are no zero byte intervals.  So we just see a lot of zero byte intervals in the fleet because most machines have low test rates (less than 2/minute)

**Comment by pboothe** [comment]
Closed, now understood. Most of our fleet was/is idle

**Comment by pboothe** [comment]
Future note: better name for the bug please
