### ISSUE TITLE
Unexplained IPv6 connection counts during load testing

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/tcp-info#112]
During load testing, I observed an unexplained increase in the number of IPv6 connections reported for mlab3.lga0t -- nearly the same as the number of V4 addrs.

For the load testing, clients explicitly use the v4 decorated hostname: ndt-iupui-mlab3v4-lga0t.measurement-lab.org

The clients ran NDT5 websocket tests on port 3001 -- so this should / can not be some artifact of TLS validation.

Reporting this on tcp-info b/c is it possible that streams are double counted as both v4 and v6 as a result of the Go server listening with IPv4-mapped IPv6. i.e. `net.Listen("tcp", server.Addr)`

The rate was calculated using:

```
rate(tcpinfo_connection_count_histogram_sum[2m])  / 
     rate(tcpinfo_connection_count_histogram_count[2m])
```

![avg-connections](https://user-images.githubusercontent.com/1085316/69466372-db3de480-0d51-11ea-8d3b-c62401ab6389.png)

**Comment by stephen-soltesz** [comment]
This double accounting was not observed on the client side -- only the server side. As well, the server machine saw disk I/O ~3x either client machine. There were only 2 clients.

**Comment by pboothe** [comment]
Counting localhost may be confusing everything.

**Comment by stephen-soltesz** [comment]
Yes, we think this is due to the non-TLS websocket proxy from port 3001 (dual stack sockets which report as IPv6 in the counts) to port 127.0.0.1:3002 (which is single stack and reports as IPv4). We were originally using non-TLS websocket tests so every connection was counted twice but as different AFs.
