### ISSUE TITLE
anonymize should not be applied to the local server address

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/tcp-info#115]
https://github.com/m-lab/tcp-info/issues/114 Adds basic support for IP anonymiztion. However, both the local server and remote client IPs are anonymized. Anonymization of the server IP will make some processing ambiguous b/c some M-Lab sites share a IPv4/24 prefix.

However, the machine and site name may be discovered from the archive name or other metadata.

**Comment by pboothe** [comment]
Fixed in https://github.com/m-lab/go/pull/91
