### ISSUE TITLE
Make tcp-info future proof

### ISSUE THREAD

**Issue by gfr10598** [m-lab/tcp-info#52]
The prototype uses protobufs to encode the netlink messages.  This means that any errors in the encoding, or new fields introduced upstream, may lead to lost data.

We should instead encode the messages at a level that is stable and won't lead to lost data.  Options include encoding the raw netlink messages, or parsing the top level netlink message protocol and saving the headers and RouteAttr messages.

**Comment by pboothe** [comment]
We are moving to JSON encoding of raw bytes.  Should be future proof.
