### ISSUE TITLE
Is there any tool to visualize the data?

### ISSUE THREAD

**Issue by dimm0** [m-lab/tcp-info#89]
I'm getting a bunch of small files from tcp-info. What can I do with them?

**Comment by gfr10598** [comment]
Hi Dmitry,
  The tool itself is in beta use in our new M-Lab platform, and we intend to encourage its used by third parties, but have only minimal support at this time.

  We've recently started importing this data into bigquery tables, but have not published those tables yet.  There is also a primitive csv tool in the cmd/ directory that will dump the files to csv files.  Currently that tool only handles a single zstd file, but we intend to extend it to handle tar files containing zstd files, and have it extract the summary info and final snapshot from each file.

We would very much like to see others using these tools, so please tell us more about your use case, and we may be able to prioritize work to support that.

**Comment by gfr10598** [comment]
FYI, on our system we use this in combination with our "pusher" tool (https://github.com/m-lab/pusher) to collect these small files into tar files.

**Comment by dimm0** [comment]
We have a global kubernetes cluster (http://ucsd-prp.gitlab.io/nautilus/cluster-map/) providing computational resources to researchers, and would like having a network monitoring tool to discover issues and having general statistics.
It was fairly easy to install tcp-info on all nodes as a daemon set, and I was trying to figure out what should I do with those millions of files it's dumping in our storage now.
I saw the csv export tool, but as you said, it's not too useful for general monitoring.
I'd love to try the tool you have and install it in our cluster

**Comment by dimm0** [comment]
Our NSF program director wants us to use tcp-info :)

**Comment by critzo** [comment]
this has been answered. closing and archiving.

**Comment by dimm0** [comment]
I still don't have a tool to use.. What do you mean it has been answered?

**Comment by critzo** [comment]
Sorry about that. This comment was made in error.

M-Lab is not developing a tool to visualize tcp-info data. We're using
tcp-info to collect metrics on connections to our servers. Perhaps @gfr has
more to say about possible tools being used internally.
