### ISSUE TITLE
bug: histogram sum incrementing by 8*2^64 in "host" context.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/tcp-info#98]
Somehow, the tcp rate histograms in the host context are getting what appears to be an observation of 1<<67, which shouldn't be possible, since the counters are uint64, and observations and sum are float64.  This occurred 24 times on 7 lgaNt machines in first two hours after boot, ranging from 2 to 6 times on each machine.

Related to m-lab/dev-tracker#322

**Comment by gfr10598** [comment]
Looks like we are seeing this in ndt containers as well, but less frequently.  Just 7 occurrences in 3 containers in 8 hours.

Mechanically, this can occur only if there are very large values reported repeatedly over the one minute prometheus collection interval.  Since there are 60 observations per minute, it might happen if all the observations had e.g. 1<<61, or half the observations had 1<<62, etc.  If this were the case, though, we would expect granularity to be less than 1<<64, instead of 1<<67.

We would also expect this to change the ability of the float64 to accumulate small changes, since float64 has only 53 bit mantissa.  So after sum exceeds 1<<67, we would expect it to only accumulate increments larger than 1<<14, which is 16kbps.  The observed bit rate increment for mlab4.lga1t is between 5 kbps and 60 kbps.  This means that in some sample intervals, there is less than 300kbits accumulated.  This could very well happen with a few medium size observations.

**Comment by gfr10598** [comment]
To see increments in the sum, there must be increments larger than the float64 resolution.  When the sum is 1<<67, the resolution is 1<<15.  So there must be some bins >= 1<<15 (32K) being incremented in order to see that increase.

Grafana does something clever (or prometheus does) with "le" queries, which complicates interpreting raw counts.
By looking at rates of bucket counts, we can show pretty clearly that the 0 bucket (mlab4.lga1t) is incrementing about 85% of the intervals.  The largest bucket that shows up on grafana is le 794000, which is incrementing about 99.8% of the time - so there are very rarely any observations larger than this.
The 100K bucket is incrementing about 95% of the time, and the 10K bucket is incrementing about 85% of the time, so the majority of the non-zero observations are falling between 10k and 100k, with a smaller number in the 100K - 1M range.  So the fact 1<<15 sensitivity will likely mean that we are already losing a lot of the increments after a single large observation, and therefore the observed rate(_sum) will be quite inaccurate.

**Comment by gfr10598** [comment]
Turns out I could see this on my workstation as well...

BUG:  Discovered that sometimes the total bytes value gets smaller.  Then subtracting larger uint64 from smaller uint64 causes a very large value to be reported to prometheus.  Added code to prevent this reporting, but need to identify the root cause.

**Comment by gfr10598** [comment]
#99

**Comment by gfr10598** [comment]
The problem is that tcpinfo resets the counter when the state changes to FIN_WAIT2.  We only see this state rarely, so the glitch only happens occasionally.

**Comment by gfr10598** [comment]
Not sufficient just to capture the FIN_WAIT2.  Instead should detect reduction in the byte counts.
Here are some with non-zero counts.
2019/08/21 16:43:57 saver.go:487: Closing: 19609069 ESTABLISHED 393 3514
2019/08/21 16:43:57 saver.go:324: sent: {live4:1896866 live6:35507713 closed:54739004} -> {live4:1896866 live6:35507886 closed:54738831}
2019/08/21 16:43:57 saver.go:324: received: {live4:4235003 live6:125794965 closed:216087222} -> {live4:4235003 live6:125795848 closed:216086339}
2019/08/21 16:43:57 saver.go:376: Closed:  19609069 FIN_WAIT2 566 4397

2019/08/21 15:22:44 saver.go:487: Closing: 19601474 FIN_WAIT1 3699 441
2019/08/21 15:22:44 saver.go:324: received: {live4:4075792 live6:116519597 closed:105858021} -> {live4:4075792 live6:116519598 closed:105858020}
2019/08/21 15:22:44 saver.go:376: Closed:  19601474 FIN_WAIT2 3699 442

2019/08/21 17:24:02 saver.go:487: Closing: 19612885 FIN_WAIT1 3699 441
2019/08/21 17:24:02 saver.go:324: received: {live4:4341648 live6:126299624 closed:434069865} -> {live4:4341648 live6:126299625 closed:434069864}
2019/08/21 17:24:02 saver.go:376: Closed:  19612885 FIN_WAIT2 3699 442

**Comment by gfr10598** [comment]
https://github.com/m-lab/tcp-info/pull/103

**Comment by pboothe** [comment]
Fixed a long time ago
